apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: akashhulke/frontendprod:0aecec1613821c91e5b227058b9ea59243a5a9ee
          imagePullPolicy: Always
          ports:
            - containerPort: 80