apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: akashhulke/frontendprod:327c286bc779d18b453857fbe4942c42ccbccf4b
          imagePullPolicy: Always
          ports:
            - containerPort: 80