apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: akashhulke/frontendprod:cfa25583f8c33d42f2c2ba51c131ce9f29d6bd2c
          imagePullPolicy: Always
          ports:
            - containerPort: 80